services:
  # Main application service
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cognitive-workflow-app
    ports:
      - "${SERVER_PORT:-8080}:8080"
    env_file:
      - .env
    profiles:
      - app
    
  # Development/Test runner service
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cognitive-workflow-dev
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    env_file:
      - .env
    working_dir: /app
    command: tail -f /dev/null  # Keep container running
    profiles:
      - dev
    
  # E2E test runner
  e2e-test:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: cognitive-workflow-e2e
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    env_file:
      - .env
    working_dir: /app
    command: mvn test -Dgroups=e2e
    profiles:
      - e2e

volumes:
  maven_cache:

