#logging:
  #level:
    #root: DEBUG

spring:
  config:
    activate:
      on-profile: test

  data:
    mongodb:
      uri: ${MONGO_TEST_URI}




# LLM
default-api-keys:
  openai: ${OPENAI_API_KEY}
  anthropic: ${ANTHROPIC_API_KEY}