logging:
  level:
    # Enable debug logging
    root: DEBUG


spring:
  config:
    activate:
      on-profile: test

  data:
    mongodb:
      # Override MongoDB URI for tests TODO
      uri: ${MONGO_URI}